baseURL = "https://docops-hq.github.io/conf/"
languageCode = "en-us"
title = "Конспекты"
theme = "tale-hugo"
[taxonomies]
    tag = "tags"
    category = "categories"
[outputs]
  home = ["HTML", "JSON", "RSS"]
  blog = ["HTML", "JSON", "RSS"]
[Params]
css = ["custom.css"]
